spring:
  application:
    name: plataforma-pesquisas

  mail:
    host: smtp.gmail.com
    port: 587
    username: enzozorzanlima@gmail.com
    password: vhfo ydxy ufrl lxiu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/platformdb
    username: postgres
    password: masterkey

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 8081

# PERFIS
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/platformdb_dev
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  realm: platform
  auth-server-url: http://localhost:8080
  resource: platform-backend
  public-client: false
  credentials:
    secret: CHAVE_SECRETA_DO_CLIENTE
  security-constraints:
    - authRoles: ["ROLE_ADMIN","ROLE_USER"]
      securityCollections:
        - patterns: ["/api/v1/*"]

---
spring:
  config:
    activate:
      on-profile: homolog

  datasource:
    url: jdbc:postgresql://homolog-db:5432/platformdb_homolog
    username: homolog
    password: homolog

  jpa:
    hibernate:
      ddl-auto: validate

keycloak:
  realm: platform
  auth-server-url: https://keycloak-homolog.suaempresa.com
  resource: platform-backend
  public-client: false
  credentials:
    secret: HOMOLOG_SECRET
  security-constraints:
    - authRoles: ["ROLE_ADMIN","ROLE_USER"]
      securityCollections:
        - patterns: ["/api/v1/*"]

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://prod-db:5432/platformdb
    username: prod
    password: prod

  jpa:
    hibernate:
      ddl-auto: validate

keycloak:
  realm: platform
  auth-server-url: https://keycloak.suaempresa.com
  resource: platform-backend
  public-client: false
  credentials:
    secret: PROD_SECRET
  security-constraints:
    - authRoles: ["ROLE_ADMIN","ROLE_USER"]
      securityCollections:
        - patterns: ["/api/v1/*"]
